# Language: Russian
---
outlines:
    default:       { width: 40.41,   height: 52     }
    action:        { width: 40.41,   height: 52     }
    change-view:   { width: 60.615,  height: 52     }
    change-view-2: { width: 40.41,   height: 52     }
    halfwidth:     { width: 20.205,  height: 52     }
    large:         { width: 40.41,   height: 52     }
    narrow:        { width: 30.307,  height: 52     }
    spaceline:     { width: 161.64,  height: 52     }
    special:       { width: 40.41,   height: 52     }
    special-2:     { width: 60.615,  height: 52     }
    special-3:     { width: 60.615,  height: 52     }
views:
    base:
        - "Esc Tab-small Ctrl Alt Shift : ь ъ ш щ"
        - "1 2 3 4 5 6 7 8 9 0"
        - "я ж ф п г й л у ы ю"
        - "а р с т д ч н е и о"
        - "show_upper з х ц в б к м э BackSpaceSmall"
        - "show_numbers comma preferences space dot Return"
    upper:
        - "Esc Tab-small Ctrl Alt Shift : ь ъ ш щ"
        - "F1  F2  F3  F4  F5 ; Ь Ъ Ш Щ"
        - "Я Ж Ф П Г Й Л У Ы Ю"
        - "А Р С Т Д Ч Н Е И О"
        - "show_upper З Х Ц В Б К М Э BackSpaceSmall"
        - "show_numbers comma preferences space dot Return"
    numbers:
        - "Esc Tab-small Ctrl Alt Shift : ↑ ↓ ← →"
        - "1 2 3 4 5 6 7 8 9 0"
        - "% / | = [ ] < > { }"
        - "@ # $ & \\ _ - + ( )"
        - "show_symbols * \" ' : ; ! ? BackSpace"
        - "show_letters comma preferences space dot Return"
    symbols:
        - "Esc Tab-small Ctrl Alt Shift : Menu Break Pause Insert"
        - "1 2 3 4 5 6 7 8 9 0"
        - "~ ` · √ π τ ÷ × ¶ @"
        - "\\ © ® £ € ¥ ^ ° { }"
        - "show_numbers_from_symbols % | < > = [ ] BackSpace"
        - "show_letters comma preferences space . Return"
buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "special"
        icon: "key-shift"
    BackSpace:
        outline: "special-2"
        icon: "edit-clear-symbolic"
        action: "erase"
    BackSpaceSmall:
        outline: "special"
        icon: "edit-clear-symbolic"
        action: "erase"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "change-view"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "change-view"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "change-view"
        label: "ABC"
    show_letters_actions:
        action:
            set_view: "base"
        outline: "change-view-2"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "change-view"
        label: "τ=\\"
    show_actions:
        action:
            set_view: "actions"
        outline: "special"
        label: ">_"
    .:
        outline: "large"
    space:
        outline: "spaceline"
        text: " "
    comma:
        text: ","
        outline: "special"
    dot:
        text: "."
        outline: "special"
    Return:
        outline: "special-3"
        icon: "key-enter"
        keysym: "Return"
    F1:
        outline: "action"
        keysym: "F1"
    F2:
        outline: "action"
        keysym: "F2"
    F3:
        outline: "action"
        keysym: "F3"
    F4:
        outline: "action"
        keysym: "F4"
    F5:
        outline: "action"
        keysym: "F5"
    F6:
        outline: "action"
        keysym: "F6"
    F7:
        outline: "action"
        keysym: "F7"
    F8:
        outline: "action"
        keysym: "F8"
    F9:
        outline: "action"
        keysym: "F9"
    F10:
        outline: "action"
        keysym: "F10"
    F11:
        outline: "action"
        keysym: "F11"
    F12:
        outline: "action"
        keysym: "F12"
    Esc:
        outline: "small-row"
        keysym: "Escape"
    Tab:
        outline: "small-row"
        keysym: "Tab"
    Tab-small:
        outline: "small-row"
        keysym: "Tab"
        label: "Tab"
    Del:
        outline: "action"
        keysym: "Delete"
    Insert:
        outline: "action"
        keysym: "Insert"
    Menu:
        outline: "action"
        keysym: "Menu"
    Pause:
        outline: "action"
        keysym: "Pause"
    Break:
        outline: "action"
        keysym: "Break"
    Home:
        outline: "small-row"
        keysym: "Home"
        label: "h←"
    End:
        outline: "small-row"
        keysym: "End"
        label: "e→"
    PageUp:
        outline: "small-row"
        keysym: "Page_Up"
        label: "p↑"
    PageDown:
        outline: "small-row"
        keysym: "Page_Down"
        label: "p↓"
    "↑":
        outline: "small-row"
        keysym: "Up"
    "↓":
        outline: "small-row"
        keysym: "Down"
    "←":
        outline: "small-row"
        keysym: "Left"
    "→":
        outline: "small-row"
        keysym: "Right"
    Up:
        label: "↑"
        outline: "action"
        keysym: "Up"
    Left:
        label: "←"
        outline: "action"
        keysym: "Left"
    Down:
        label: "↓"
        outline: "action"
        keysym: "Down"
    Right:
        label: "→"
        outline: "action"
        keysym: "Right"
    Ctrl:
        modifier: "Control"
        outline: "small-row"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "small-row"
        label: "Alt"
    Shift:
        modifier: "Shift"
        outline: "small-row"
        label: "Shift"

