- name: gnome
  hosts: all
  vars_files:
    - vault.yml
  tasks:
    - name: gnome
      shell: |
        gsettings set org.gnome.desktop.interface color-scheme prefer-dark
        gsettings set org.gnome.desktop.input-sources show-all-sources true
        gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us+colemak'), ('xkb', 'ru+rulemak')]"
        gsettings set org.gnome.desktop.interface font-name 'AdwaitaSans Nerd Font 16'
        gsettings set org.gnome.desktop.interface document-font-name 'AdwaitaSans Nerd Font 16'
        gsettings set org.gnome.desktop.interface monospace-font-name 'AdwaitaMono Nerd Font 16'
        gsettings set org.gnome.desktop.interface clock-format '24h'

