- name: font
  hosts: all
  gather_facts: yes
  tasks:
    - name: mkdir fonts
      file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: 0755
    - name: mkdir jbm
      file:
        path: /tmp/jbm
        state: directory
        mode: 0755
    - name: download
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
        dest: /tmp/jbm/JetBrainsMono.tar.xz
    - name: unpack
      command: tar -xf /tmp/jbm/JetBrainsMono.tar.xz -C /tmp/jbm
    - name: copy
      copy:
        src: /tmp/jbm/JetBrainsMonoNerdFont-Regular.ttf
        dest: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf"
        remote_src: yes
        mode: 0644

