- name: pmos-apps
  hosts: all
  become: yes
  become_method: doas
  vars_files:
    - vault.yml
  tasks:
    - name: ispmos
      command: grep -q "postmarketos" /etc/os-release
      register: ispmos
      changed_when: false
      failed_when: false
    - name: pmos-apps
      when: ispmos.rc == 0
      block:
        - name: upgrade
          apk:
            update_cache: yes
            upgrade: yes
        - name: remove
          apk:
            update_cache: yes
            name:
              - postmarketos-welcome
              - gnome-text-editor
              - gnome-calendar
              - gnome-weather
              - gnome-clocks
              - gnome-maps
              - showtime
              - decibels
              - papers
              - loupe
            state: absent
        - name: install
          apk:
            update_cache: yes
            name:
              - gnome-software-plugin-flatpak
              - ffmpegthumbnailer
              - fastfetch
              - distrobox
              - waydroid
              - flatpak
              - podman
              - curl
              - tmux
              - fish
              - git
            state: latest

