- name: zram generator conf
  become: yes
  copy:
    src: ../root/etc/systemd/zram-generator.conf
    dest: /etc/systemd/zram-generator.conf
  register: zram
- name: daemon reload
  when: zram.changed
  become: yes
  systemd:
    daemon_reload: yes
- name: restart zram setup
  when: zram.changed
  become: yes
  systemd:
    name: systemd-zram-setup@zram0.service
    state: restarted

